### ISSUE TITLE
Does it work with SASS?

### ISSUE THREAD

**Issue by doasync** [YozhikM/stylelint-a11y#31]
I am using a recommended config. I've configured WebStorm. Here is an error I get:

```bash
TypeError: Cannot read property 'toLowerCase' of undefined
    at ~/projects/my-project/node_modules/stylelint-a11y/dist/rules/no-spread-text/index.js:66:17
    at Array.map (<anonymous>)
    at nodesProbablyForText (~/projects/my-project/node_modules/stylelint-a11y/dist/rules/no-spread-text/index.js:65:6)
    at ~/projects/my-project/node_modules/stylelint-a11y/dist/rules/no-spread-text/index.js:27:24
    at ~/projects/my-project/node_modules/postcss/lib/container.js:237:28
    at ~/projects/my-project/node_modules/postcss/lib/container.js:144:26
    at Root.each (~/projects/my-project/node_modules/postcss/lib/container.js:110:22)
    at Root.walk (~/projects/my-project/node_modules/postcss/lib/container.js:143:21)
    at Root.walkRules (~/projects/my-project/node_modules/postcss/lib/container.js:235:25)
    at ~/projects/my-project/node_modules/stylelint-a11y/dist/rules/no-spread-text/index.js:16:10
```
sass file:

```sass
.x__y-z {
  .gr-col {
    position: relative;
    padding-right: 1rem;
    padding-left: 1rem;
    min-height: .0625rem;
    width: 100%;

    &__1 {
      flex-grow: 0;
      flex-shrink: 0;
      flex-basis: 100%;
      max-width: 100%;
      -ms-flex-positive: 0;
      -ms-flex-negative: 0;
      -ms-flex-preferred-size: 100%;
    }

    &__gutter{
      &--0 {
        padding-right: 0;
        padding-left: 0;
      }
    }
  }
}
```
Does it work with SASS?

**Comment by YozhikM** [comment]
Thank you for the reported issue! I will fix it ASAP

**Comment by YozhikM** [comment]
Fixed in 1.1.7. Tell me if you find regression.

**Comment by doasync** [comment]
Thanks, I'll check it out later

**Comment by GAS2** [comment]
I have a similar issue when using this plugin with styled-components.

- node: v8.11.2
- npm: 5.6.0
- stylelint-a11y: 1.1.7
- styled-components: 3.3.3

```jsx
const Button = styled.button`
	padding: 0.5em 1.5em;
	font-size: 1em;
	
	background-color: var(--background-color, hsl(0, 0%, 100%));
	background-image: var(--background-image, none);
	
	border: 0.125em solid var(--border-color, hsl(0, 0%, 40%));
	border-radius: 0.1875em;
	
	color: var(--color, hsl(0, 0%, 40%));
	cursor: pointer;
	
	&:hover {
		--background-color: hsl(0, 0%, 80%);
		--color: hsl(0, 0%, 20%);
		--border-color: hsl(0, 0%, 20%)
	}
	
	&:active {
		--background-color: hsl(0, 0%, 60%);
		--color: hsl(0, 0%, 0%);
		--border-color: hsl(0, 0%, 0%)
	}
	
	&:focus {
		--background-color: hsl(0, 0%, 60%);
		--color: hsl(0, 0%, 0%);
		--border-color: hsl(0, 0%, 0%);
		
		outline: none;
		box-shadow: 0 0 0.125em 0.25em highlight;
	}
`;
```


```
TypeError: Cannot read property 'toLowerCase' of undefined
    at /Users/greada/Workspace/Sinnerschrader/collaboard/node_modules/stylelint-a11y/dist/rules/content-property-no-static-value/index.js:72:22
    at Array.some (<anonymous>)
    at checkNodesForContentProperty (/Users/greada/Workspace/Sinnerschrader/collaboard/node_modules/stylelint-a11y/dist/rules/content-property-no-static-value/index.js:71:21)
    at check (/Users/greada/Workspace/Sinnerschrader/collaboard/node_modules/stylelint-a11y/dist/rules/content-property-no-static-value/index.js:77:32)
    at /Users/greada/Workspace/Sinnerschrader/collaboard/node_modules/stylelint-a11y/dist/rules/content-property-no-static-value/index.js:32:24
    at /Users/greada/Workspace/Sinnerschrader/collaboard/node_modules/stylelint/node_modules/postcss/lib/container.js:144:26
    at Root.each (/Users/greada/Workspace/Sinnerschrader/collaboard/node_modules/stylelint/node_modules/postcss/lib/container.js:110:22)
    at Root.walk (/Users/greada/Workspace/Sinnerschrader/collaboard/node_modules/stylelint/node_modules/postcss/lib/container.js:143:21)
    at /Users/greada/Workspace/Sinnerschrader/collaboard/node_modules/stylelint-a11y/dist/rules/content-property-no-static-value/index.js:16:10
    at Promise.resolve.then (/Users/greada/Workspace/Sinnerschrader/collaboard/node_modules/stylelint/lib/lintSource.js:221:9)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by kabadesu** [comment]
I'm hitting this issue with scss in v1.1.7.

Running node 10.8.0, npm 6.4.0.

Message is:

```
Message:
    Cannot read property 'toLowerCase' of undefined
Details:
    postcssNode: .container {
    position: relative;
    max-width: $max-width-desktop;
    margin-left: auto;
    margin-right: auto;
    padding-left: 20px;
    padding-right: 20px;

    @media (min-width: 600px) {
        padding-left: 24px;
        padding-right: 24px;
    }
}
```

```
(node:12195) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'toLowerCase' of undefined
    at /PATH/src/scss/components/_container.scss:1:1
    at /PATH/node_modules/stylelint-a11y/dist/rules/content-property-no-static-value/index.js:72:22
```
